version: "3.9"
services:
  postgres:
    image: postgres:16.1-alpine3.18
    environment:
      POSTGRES_PASSWORD: "secret"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
